In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
import matplotlib.pyplot as plt
import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

[]


![](http://r2rt.com/static/images/RNN_MultiRNNCellUngrouped.png)

In [2]:
#In MultiRNN cell : hidden layer of bottom RNN is fed to RNN cell above it and so on
#Depending upon number of cells provided as a list in MultiRNN cell
#MultiRNN cell Wraps whole list of BasicRNN cells .sort of like box 


![](https://r2rt.com/static/images/RNN_MultiRNNCellGrouped.png)

In [3]:
 # Image taken from  https://r2rt.com/

In [5]:
X_data = np.array([

        [[1, 2], [7, 8], [13, 14]],  
        [[3, 4], [9, 10], [15, 16]],
        [[5, 6], [11, 12], [17, 18]]])

In [6]:
n_neurons=8
n_steps=X_data.shape[1]
n_inputs=X_data.shape[2]
n_layers=5

X=tf.placeholder(tf.float32,[None,n_steps,n_inputs])
layers=[tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons) for i in range(n_layers)]
multi_cell=tf.nn.rnn_cell.MultiRNNCell(layers)
output,state=tf.nn.dynamic_rnn(multi_cell,X,dtype=tf.float32)

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.


In [8]:
init=tf.global_variables_initializer()
with tf.Session() as s:
    s.run(init)
    feed_dict={X:X_data}
    output1,state1=s.run([output,state],feed_dict=feed_dict)

In [9]:
output1.shape

(3, 3, 8)

In [15]:
print(len(state1))


5


In [18]:
output1[:,2,:]

array([[-0.10288267, -0.38434651,  0.16299744,  0.09441876,  0.0266283 ,
         0.34535977, -0.38796043, -0.1862032 ],
       [-0.13499536, -0.27170727,  0.24019115,  0.01952399, -0.03292025,
         0.26523814, -0.3804391 , -0.12422167],
       [-0.1288587 , -0.2675806 ,  0.24263893,  0.00318548, -0.0178283 ,
         0.27111962, -0.39168665, -0.12813908]], dtype=float32)

In [19]:
state1 

(array([[-0.81237864, -0.98997456,  0.9998835 , -0.96649325,  0.99991834,
         -0.5070641 ,  0.980906  , -0.9998321 ],
        [-0.8732774 , -0.9949179 ,  0.9999638 , -0.97367555,  0.9999816 ,
         -0.5867789 ,  0.9888569 , -0.99995863],
        [-0.91395676, -0.99791306,  0.9999869 , -0.9795536 ,  0.99999607,
         -0.5836412 ,  0.993817  , -0.99998933]], dtype=float32),
 array([[ 0.05820724,  0.13304314,  0.54604685, -0.3548285 ,  0.07028165,
         -0.496838  , -0.51755786,  0.07451226],
        [ 0.16994385,  0.20003669,  0.61265224, -0.41911528,  0.26181167,
         -0.4765458 , -0.5108947 , -0.09600033],
        [ 0.18784487,  0.2023045 ,  0.63330394, -0.45297325,  0.2697069 ,
         -0.45146546, -0.50672585, -0.11064941]], dtype=float32),
 array([[-0.05463859,  0.01332746, -0.6525228 ,  0.19745716,  0.5737965 ,
          0.8435214 , -0.12628067,  0.35465512],
        [ 0.02320506, -0.01218486, -0.6579571 , -0.04774509,  0.67092454,
          0.8661538 , -0.003251

In [20]:
#output1 is giving hidden state of only top RNN cells at different timestamps
# state1 is giving hidden state of all RNN cells in MultiRNN across all batches but in last time stamp
#starting from bottom RNN cell state as first element and top RNN cell state as the last element
# so last timestamp state of output1 is same as last element of state1

In [23]:
output1[:,2,:]

array([[-0.10288267, -0.38434651,  0.16299744,  0.09441876,  0.0266283 ,
         0.34535977, -0.38796043, -0.1862032 ],
       [-0.13499536, -0.27170727,  0.24019115,  0.01952399, -0.03292025,
         0.26523814, -0.3804391 , -0.12422167],
       [-0.1288587 , -0.2675806 ,  0.24263893,  0.00318548, -0.0178283 ,
         0.27111962, -0.39168665, -0.12813908]], dtype=float32)

In [24]:
state1[-1]

array([[-0.10288267, -0.38434651,  0.16299744,  0.09441876,  0.0266283 ,
         0.34535977, -0.38796043, -0.1862032 ],
       [-0.13499536, -0.27170727,  0.24019115,  0.01952399, -0.03292025,
         0.26523814, -0.3804391 , -0.12422167],
       [-0.1288587 , -0.2675806 ,  0.24263893,  0.00318548, -0.0178283 ,
         0.27111962, -0.39168665, -0.12813908]], dtype=float32)

In [25]:
#Both are same