In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

[]


In [2]:
seq_length=tf.placeholder(tf.int32,[None])
X_batch = np.array([
# step 0 step 1
[[0, 1, 2], [9, 8, 7]], # instance 0
[[3, 4, 5], [0, 0, 0]], # instance 1 (padded with a zero vector)
[[6, 7, 8], [6, 5, 4]], # instance 2
[[9, 0, 1], [3, 2, 1]], # instance 3
])
seq_length_batch = np.array([2, 1, 2, 2])

In [3]:
X=tf.placeholder(tf.float32,[None,2,3])

In [4]:
X_batch.shape
outputs,state=tf.nn.dynamic_rnn(tf.nn.rnn_cell.BasicRNNCell(8),X,dtype=tf.float32,sequence_length=seq_length)

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.


In [5]:
#batch size =4
# no of timestamps 2
# n inputs=3
init=tf.global_variables_initializer()

In [6]:
with tf.Session() as s:
    s.run(init)
    output1,state1=s.run([outputs,state],feed_dict={X:X_batch,seq_length:seq_length_batch})
    

In [7]:
output1.shape  #so dynamic rnn pad other sequences length with zeros


(4, 2, 8)

In [8]:
output1[:,1,:]

array([[ 1.        ,  0.9825132 , -0.95549846, -0.46331474,  0.97516966,
        -0.9999999 ,  0.9967437 , -0.8689447 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.99998814,  0.5695395 , -0.9005881 , -0.23025082,  0.72811466,
        -0.9999641 ,  0.9872708 ,  0.52159077],
       [ 0.98783207,  0.9399032 , -0.977491  , -0.1371896 , -0.53114766,
        -0.9954591 ,  0.8742806 , -0.4050319 ]], dtype=float32)

In [9]:
state1

array([[ 1.        ,  0.9825132 , -0.95549846, -0.46331474,  0.97516966,
        -0.9999999 ,  0.9967437 , -0.8689447 ],
       [ 0.9997875 ,  0.8495464 , -0.6837264 ,  0.544235  ,  0.9597583 ,
        -0.9999158 ,  0.39711648, -0.899459  ],
       [ 0.99998814,  0.5695395 , -0.9005881 , -0.23025082,  0.72811466,
        -0.9999641 ,  0.9872708 ,  0.52159077],
       [ 0.98783207,  0.9399032 , -0.977491  , -0.1371896 , -0.53114766,
        -0.9954591 ,  0.8742806 , -0.4050319 ]], dtype=float32)

In [10]:
output1[1,0,:]  #state is going to give last non zero hidden state of dynamic rnn

array([ 0.9997875 ,  0.8495464 , -0.6837264 ,  0.544235  ,  0.9597583 ,
       -0.9999158 ,  0.39711648, -0.899459  ], dtype=float32)